/** 블록이 아닌 아이템은 100번부터 쓴다 (블록은 블록 번호 그대로). */
export const Item = {
  Meat: 100,
  /** 검 (예전 "몽둥이"). 저장된 게임과 번호를 맞추려고 옛 이름을 그대로 둔다. */
  WoodClub: 101,
  StoneClub: 102,
  Bed: 103,
  IronClub: 104,
  CookedMeat: 105,
  Grain: 106,
  Bread: 107,
  Stick: 108,
  WoodPickaxe: 110,
  StonePickaxe: 111,
  IronPickaxe: 112,
  WoodAxe: 113,
  StoneAxe: 114,
  IronAxe: 115,
  WoodShovel: 116,
  StoneShovel: 117,
  IronShovel: 118,
  IronIngot: 119,
  Bone: 120,
  Gunpowder: 121,
  Diamond: 122,
  DiamondPickaxe: 123,
  DiamondAxe: 124,
  DiamondShovel: 125,
  DiamondClub: 126,
  IronHelmet: 127,
  IronChestplate: 128,
  IronLeggings: 129,
  IronBoots: 130,
  DiamondHelmet: 131,
  DiamondChestplate: 132,
  DiamondLeggings: 133,
  DiamondBoots: 134,
  Bow: 135,
  Arrow: 136,
  RawFish: 137,
  CookedFish: 138,
  DragonHorn: 139,
  DragonScale: 140,
  Coal: 141,
  GlassBottle: 142,
  HealPotion: 143,
  SpeedPotion: 144,
  StrengthPotion: 145,
  RegenPotion: 146,
  String: 147,
  FishingRod: 148,
  Emerald: 149,
  Saddle: 150,
  Shield: 151,
  PigEgg: 160,
  SheepEgg: 161,
  HorseEgg: 162,
  WolfEgg: 163,
  VillagerEgg: 164,
  ZombieEgg: 165,
  SkeletonEgg: 166,
  CreeperEgg: 167,
  SpiderEgg: 168,
  FishEgg: 169,
  DragonEgg: 170,
} as const;

export const ITEM_NAMES: Record<number, string> = {
  [Item.Meat]: "고기",
  [Item.WoodClub]: "나무 검",
  [Item.StoneClub]: "돌 검",
  [Item.Bed]: "침대",
  [Item.IronClub]: "철 검",
  [Item.CookedMeat]: "구운 고기",
  [Item.Grain]: "밀",
  [Item.Bread]: "빵",
  [Item.Stick]: "막대",
  [Item.WoodPickaxe]: "나무 곡괭이",
  [Item.StonePickaxe]: "돌 곡괭이",
  [Item.IronPickaxe]: "철 곡괭이",
  [Item.WoodAxe]: "나무 도끼",
  [Item.StoneAxe]: "돌 도끼",
  [Item.IronAxe]: "철 도끼",
  [Item.WoodShovel]: "나무 삽",
  [Item.StoneShovel]: "돌 삽",
  [Item.IronShovel]: "철 삽",
  [Item.IronIngot]: "철 주괴",
  [Item.Bone]: "뼈",
  [Item.Gunpowder]: "화약",
  [Item.Diamond]: "다이아몬드",
  [Item.DiamondPickaxe]: "다이아몬드 곡괭이",
  [Item.DiamondAxe]: "다이아몬드 도끼",
  [Item.DiamondShovel]: "다이아몬드 삽",
  [Item.DiamondClub]: "다이아몬드 검",
  [Item.IronHelmet]: "철 투구",
  [Item.IronChestplate]: "철 흉갑",
  [Item.IronLeggings]: "철 바지",
  [Item.IronBoots]: "철 부츠",
  [Item.DiamondHelmet]: "다이아몬드 투구",
  [Item.DiamondChestplate]: "다이아몬드 흉갑",
  [Item.DiamondLeggings]: "다이아몬드 바지",
  [Item.DiamondBoots]: "다이아몬드 부츠",
  [Item.Bow]: "활",
  [Item.Arrow]: "화살",
  [Item.RawFish]: "물고기",
  [Item.CookedFish]: "구운 물고기",
  [Item.DragonHorn]: "용의 뿔",
  [Item.DragonScale]: "용의 비늘",
  [Item.Coal]: "석탄",
  [Item.GlassBottle]: "유리병",
  [Item.HealPotion]: "치유 물약",
  [Item.SpeedPotion]: "속도 물약",
  [Item.StrengthPotion]: "힘 물약",
  [Item.RegenPotion]: "재생 물약",
  [Item.String]: "실",
  [Item.FishingRod]: "낚싯대",
  [Item.Emerald]: "에메랄드",
  [Item.Saddle]: "안장",
  [Item.Shield]: "방패",
  [Item.PigEgg]: "돼지 알",
  [Item.SheepEgg]: "양 알",
  [Item.HorseEgg]: "말 알",
  [Item.WolfEgg]: "늑대 알",
  [Item.VillagerEgg]: "마을 사람 알",
  [Item.ZombieEgg]: "좀비 알",
  [Item.SkeletonEgg]: "해골 알",
  [Item.CreeperEgg]: "크리퍼 알",
  [Item.SpiderEgg]: "거미 알",
  [Item.FishEgg]: "물고기 알",
  [Item.DragonEgg]: "드래곤 알",
};
